name: Fetch ANAC RSS

on:
  schedule:
    - cron: '0 */1 * * *'  # Executa a cada 1h
  workflow_dispatch:      # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: ▶️ Executar script Deno para gerar JSON e HTML
        run: deno run --allow-net --allow-write deno/fetch_news.ts
      
      - name: 🛠️ Gerar RSS a partir do JSON
        run: deno run --allow-net --allow-write deno/json_to_rss.ts      

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📰 Atualiza notícias ANAC (JSON, RSS e HTML)"
          file_pattern: 'data/*'
