name: ANAC RSS Feed Generator

on:
  schedule:
    - cron: '0 */4 * * *'  # Executa a cada 4 horas
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-feed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 feedgenerator requests html2text

    - name: Generate RSS feed
      run: |
        # [Seu script Python completo aqui - mantém o mesmo conteúdo do Colab]
        python anac_rss_generator.py

    - name: Verify XML
      run: |
        if [ ! -s "anac-feed.xml" ]; then
          echo "::error::O arquivo RSS está vazio!"
          exit 1
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: anac-feed.xml

  deploy:
    needs: generate-feed
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
