# .github/workflows/anac_feed.yml
name: ANAC RSS Feed Generator

on:
  schedule:
    - cron: '0 */6 * * *'  # Atualiza a cada 6 horas
  workflow_dispatch:

jobs:
  generate-feeds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '1.40.x'

      - name: Generate JSON and RSS
        run: |
          cat << 'EOF' > script.ts
          // Script Deno inline
          import { Feed } from "https://esm.sh/feed@4.2.2";

          const ANAC_URL = "https://www.gov.br/anac/pt-br/noticias";
          
          async function fetchNews() {
            try {
              // 1. Fetch and parse HTML
              const res = await fetch(ANAC_URL);
              const html = await res.text();
              const doc = new DOMParser().parseFromString(html, "text/html");

              // 2. Extract news data
              const news = Array.from(doc.querySelectorAll("article.tileItem"))
                .slice(0, 20)
                .map((article) => ({
                  title: article.querySelector("h2 a")?.textContent?.trim() || "Sem título",
                  link: new URL(
                    article.querySelector("h2 a")?.getAttribute("href") || "#",
                    ANAC_URL
                  ).toString(),
                  description: article.querySelector("p.tileBody span")?.textContent?.trim() || "",
                  date: new Date(
                    article.querySelector(".icon-day")?.nextSibling?.textContent?.trim() || new Date()
                  ),
                }));

              // 3. Generate JSON
              await Deno.writeTextFile(
                "anac_feed.json",
                JSON.stringify({ updated: new Date(), items: news }, null, 2)
              );

              // 4. Generate RSS
              const feed = new Feed({
                title: "ANAC Notícias",
                description: "Feed RSS oficial",
                id: ANAC_URL,
                link: ANAC_URL,
                updated: new Date(),
              });

              news.forEach(item => feed.addItem({
                title: item.title,
                link: item.link,
                description: item.description,
                date: item.date,
              }));

              await Deno.writeTextFile("anac_feed.xml", feed.rss2());
              console.log("Feeds gerados com sucesso!");

            } catch (error) {
              console.error("Erro:", error);
              Deno.exit(1);
            }
          }

          await fetchNews();
          EOF

          deno run --allow-net --allow-write script.ts

      - name: Commit Results
        run: |
          mkdir -p feeds
          mv anac_feed.json feeds/anac.json
          mv anac_feed.xml feeds/anac.rss.xml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add feeds/
          git commit -m "📌 Atualiza feed ANAC [$(date +'%d/%m/%Y %H:%M')]"
          git push
