name: Fetch ANAC News

on:
  schedule:
    - cron: '0 */4 * * *'  # Executa a cada 4h
  workflow_dispatch:      # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run scraper
        run: deno run --allow-net --allow-write deno/fetch_news.ts

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📰 Atualiza notícias ANAC (JSON, RSS e HTML)"
          file_pattern: 'data/noticias.*'
